/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import Objects.MessdatenEintrag;
import Objects.MessdatenListe;
import Server.Server;
import Utility.Constants;
import Utility.DataIO;
import java.awt.Component;
import java.awt.Dimension;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Phineas Gaming
 */
public class Main extends javax.swing.JFrame {
    
    DataIO io;
    
    
    /**
     * Creates new form Main
     */
    public Main() throws IOException {
        Server.startServer("http://localhost:8080/hausverwaltung", true);
        initComponents();
        
        io = new DataIO();
        io.load();
        
        initMonitor();
        
        setExtendedState(JFrame.MAXIMIZED_BOTH); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        monitoringScrollPane = new javax.swing.JScrollPane();
        eingabePanel = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hausverwaltung");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                try {
                    Server.stopServer(true);
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
                formWindowClosing(evt);
            }
        });

        jToolBar1.setRollover(true);

        jButton1.setText("Datei");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        jButton2.setText("Hilfe");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        monitoringScrollPane.setBorder(null);
        jTabbedPane1.addTab("Monitoring", monitoringScrollPane);

        eingabePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jButton3.setText("Neuer Zähler");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        eingabePanel.add(jButton3);

        jButton4.setText("Zählerwechsel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        eingabePanel.add(jButton4);

        jTabbedPane1.addTab("Eingabe", eingabePanel);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Daten vom XX.XX.XXXX");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        NeuerZaehler neu = new NeuerZaehler(io, Constants.WECHSEL_NEIN, null);
        neu.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        NeuerZaehler alt = new NeuerZaehler(io, Constants.WECHSEL_SETZEN, null);
        alt.setTitle("Alten Zähler einlesen");
        alt.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        io.save();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Main().setVisible(true);
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel eingabePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JScrollPane monitoringScrollPane;
    // End of variables declaration//GEN-END:variables

    public void initMonitor() {
        String[] columnNames = {"Kundennummer",
                        "Hausnummer",
                        "Wohnungsnummer",
                        "Art",
                        "Zählernummer",
                        "Ablesedatum",
                        "Gewechselt",
                        "Kraftstrom in kWh",
                        "Haushaltsstrom in kWh",
                        "Kommentar"};
        
        MessdatenListe messDaten = io.getMessdatenListe();
        Object[][] data = new Object[messDaten.getMessdatenListe().size()][10];
        
        for(int i = 0; i < io.getMessdatenListe().getMessdatenListe().size(); i++)
        {
            MessdatenEintrag entry = messDaten.getMessdatenListe().get(i);
            data[i][0] = entry.getKundennr();
            data[i][1] = entry.getHausnr();
            data[i][2] = entry.getWohnungsnr();
            data[i][3] = entry.getZaehlerart();
            data[i][4] = entry.getZaehlernr();
            
            SimpleDateFormat originalFormat = new SimpleDateFormat("yyyyMMdd");
            Date date = null;
            try {
                date = originalFormat.parse(String.valueOf(entry.getAblesedatum()));
            } catch (ParseException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
            SimpleDateFormat newFormat = new SimpleDateFormat("dd.MM.yyyy");
            String formatedDate = newFormat.format(date);
            data[i][5] = formatedDate;
            
            if(entry.isZahlerwechsel()){
                data[i][6] = "Ja";
            }else{
                data[i][6] = "";
            }
            data[i][7] = entry.getZaehlerstandK();
            data[i][8] = entry.getZaehlerstandH();
            data[i][9] = entry.getKommentar();
        }
        
        JTable table = new JTable(data, columnNames);
        table.setDefaultEditor(Object.class, null);
        table.setShowVerticalLines(false);
        table.setRowHeight(20);
        
        monitoringScrollPane.setViewportView(table);
        table.setFillsViewportHeight(true);
    }
}
